### ISSUE TITLE
Improving search: multiple arguments, improved relevance?

### ISSUE THREAD

**Issue by mherger** [Qobuz/api-documentation#23]
IMHO the catalog/search method is often returning too much and rather irrelevant results. Eg. searching for "Elvis Costello" would return an album called "French Songs" by Polar. No idea how this is related to the wanted artist. Or "Ultimate Backing Tracks: Cool Rock, Vol. 5" by Soundmachine. Most of these albums have zero popularity. Wouldn't it make sense to add support for multiple arguments, eg. popularity > 10. Or search for artist and track name (or album name etc.)? I'm currently getting huge result sets searching for albums alone, when the artist/get?extra=albums would return only a dozen or two relevant albums. The result sets are sometimes so big, a Raspberry Pi would take 20-30 seconds to parse the xml.

**Comment by mherger** [comment]
Hmm... you closed this. Because it's fixed? Because you can't fix it? Would have been nice to see some feedback, too.

**Comment by lucile-bak** [comment]
Hi, sorry about that, I thought this topic was so old I could close it. It's almost an everyday work to make the algorithm more precise but to answer you, yes, we've made a lot of improvements since then.
