### ISSUE TITLE
How to determine the user's subscription level?

### ISSUE THREAD

**Issue by mherger** [Qobuz/api-documentation#33]
Hi,

user/login would return a credential data structure with a lot of information about the user's subscription. Unfortunately there's no documentation of what values to expect there and how to determine whether a user has eg. HiFi level or not. Could you please add something?

Michael

**Comment by PEM-FR** [comment]
Sublime give the same rights as HI-FI in terms of streaming. There should be no difference.

**Comment by mherger** [comment]
Thanks for the feedback. My question was more about what kind of values we can expect in the "label" field of a user's profile. I was able to figure it out with the help of a sublime user. But it would be great if the possible values and their meaning for lossless streaming were documented. Thanks again!
