### ISSUE TITLE
API returns "streamable":false for all tracks, even if they are streamable?

### ISSUE THREAD

**Issue by rolandrohde** [Qobuz/api-documentation#41]
Hi,

If I send a call to the API like this:

http://www.qobuz.com/api.json/0.2/catalog/search?app_id=100000000&query=maurice%20ravel%20la%20valse&type=tracks

I get a list of results. The first one is wrong (and not available in my country anyway so should not show up in the first place) but the others are OK. Sadly, they all show "streamable":false even though I can open them fine on the Qobuz app (Android) and the Squeezebox app. 
Is there a reason for this? Also, is there a flag that let's an app ignore albums and tracks that are unavailable in the respective country?

Thanks!

**Comment by mherger** [comment]
If you send the request using an invalid app_id, you'd get wrong streamable flags. The app_id in your link is such an invalid app_id afaik, only there for demo purposes.

**Comment by rolandrohde** [comment]
Sounds like it might be true...
