### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by rollet** [Qobuz/api-documentation#42]
Hi,

I am reading the API documentation, and it seems that all the API endpoints are only available on http, not https. In particular, login credentials are get using a HTTP request, with password simply encoded with MD5 hash. So, attack replay are very easy to do, sniffing the HTTP traffic and getting the username and MD5 password . Then, attacker can use them to get an authentication token, execute authenticated requests and so on... So, my question is quite simple, do you plan to move to HTTPS instead of HTTP for some part of the API ?

Regards,

**Comment by michaelherger** [comment]
@albadoud would have been nice if you at least had commented why you close all these issues. Hopefully these are resolved?!?
