### ISSUE TITLE
Dead link API terms of use (for http://www.qobuz.com/apps/api/QobuzAPI-TermsofUse.pdf)

### ISSUE THREAD

**Issue by JosephCaillet** [Qobuz/api-documentation#62]
http://www.qobuz.com/apps/api/QobuzAPI-TermsofUse.pdf is no longer available.

**Comment by albadoud** [comment]
Hi,

Thanks a lot, we will correct this asap.

Regards

**Comment by albadoud** [comment]
Url changed
